name: Deploy Infrastructure

on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
      GCS_BUCKET:
        required: true

env:
  PROJECT_ID: sismica-marina
  REGION: us-central1
  REGISTRY: us.gcr.io
  PROJECT_NAME: sismica-marina

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.0"

    - name: Create Service Account Key File
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp-sa-key.json

    - name: Create TFVars File
      working-directory: terraform
      run: |
        cat <<EOF > terraform.tfvars
        project_id     = "${{ env.PROJECT_ID }}"
        region         = "${{ env.REGION }}"
        project_name   = "${{ env.PROJECT_NAME }}"
        environment    = "prod"
        backend_image  = "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}-backend:${{ github.sha }}"
        frontend_image = "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}-frontend:${{ github.sha }}"
        gcs_bucket     = "${{ secrets.GCS_BUCKET }}"
        EOF

    - name: Terraform Init
      working-directory: terraform
      run: |
        BACKEND_BUCKET="sismica-marina-tf-state"
        terraform init -backend-config="bucket=${BACKEND_BUCKET}"

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -lock=false

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve -lock=false

    - name: Output Service URLs
      working-directory: terraform
      run: |
        echo "Frontend URL: $(terraform output -raw frontend_url)"
        echo "Backend URL:  $(terraform output -raw backend_url)"
